# Use container-based infrastructure
sudo: false

language: scala

matrix:
  include:
  - env: SBT_VERSION="0.13.15"
    jdk: openjdk7
    scala: 2.10.6

  - env: SBT_VERSION="1.0.0-RC2"
    jdk: oraclejdk8
    scala: 2.12.2

script:
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M ++$TRAVIS_SCALA_VERSION "^^${SBT_VERSION}" test scripted

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
