name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 21 * * 0'
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - java: 8
            scala: 2.12.8
          - java: 11
            scala: 2.12.8
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.${{ matrix.java }}"
    - uses: coursier/cache-action@v5
    - name: Build and test
      if: "!startsWith(matrix.os, 'windows')"
      run: |
        sbt -v +publishLocal ++${{matrix.scala}}! test scripted
        rm -rf "$HOME/.ivy2/local" || true
        rm -rf "$HOME/.ivy2/cache/com.eed3si9n" || true
        find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
        find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                              -name "*.lock"               -delete || true
    - name: Build and test
      if: startsWith(matrix.os, 'windows')
      run: |
        sbt -v +publishLocal ++${{matrix.scala}}! test scripted
        if (Test-Path "~/.ivy2/local") { Remove-Item -r "~/.ivy2/local" -Force }
        if (Test-Path "~/.ivy2/cache/com.eed3si9n") { Remove-Item -r "~/.ivy2/cache/com.eed3si9n" -Force }
        Get-ChildItem -Path ~/Library/Caches/Coursier/v1/**/ivydata-*.properties -Recurse -Force | Remove-Item -Verbose
        Get-ChildItem -Path ~/.ivy2/cache/**/ivydata-*.properties -Recurse -Force | Remove-Item -Verbose
        Get-ChildItem -Path ~/.cache/coursier/v1 /**/ivydata-*.properties -Recurse -Force | Remove-Item -Verbose
        Get-ChildItem -Path ~/.sbt/**/*.lock -Recurse -Force | Remove-Item -Verbose
