name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 21 * * 0'
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - java: 8
            scala: 2.12.8
          - java: 11
            scala: 2.12.8
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: "adopt"
        java-version: "${{ matrix.java }}"
    - uses: coursier/cache-action@v6
    - name: Build and test
      shell: bash
      run: |
        curl -sL https://raw.githubusercontent.com/sbt/sbt/85b18fa54832cd3d025973e86748fa834f0363f8/sbt -o sbt
        chmod +x ./sbt
        ./sbt -v +publishLocal $(if [[ "${{matrix.scala}}" != "" ]] ; then echo "++${{matrix.scala}}!" ; fi) test scripted
        rm -rf "$HOME/.ivy2/local" || true
        rm -rf "$HOME/.ivy2/cache/com.eed3si9n" || true
        find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
        find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                              -name "*.lock"               -delete || true
